name: PHPCS

on:
  push:
  workflow_dispatch:

jobs:
  run:
    name: phpcs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2']

    steps:
      - uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: pdo, pdo_mysql, zip, mysqli, gd

      - name: Install dependencies
        run: cd core/components/commerce_projectname && composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Install phpcs
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run phpcs
        run: composer run phpcs -- --runtime-set testVersion ${{ matrix.php-version }}
